#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

apt-get -y install default-jre wget curl
export LC_ALL=en_US.UTF-8
apt-get install -y software-properties-common

# Install oracle-java8:
add-apt-repository ppa:webupd8team/java
apt-get update
env DEBIAN_FRONTEND=noninteractive echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
env DEBIAN_FRONTEND=noninteractive echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes oracle-java8-installer oracle-java8-set-default
